# Generated by Django 6.0.3 on 2026-04-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usageevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='accounts_us_organiz_b11c5b_idx',
            old_name='accounts_usa_organiz_d1e8d0_idx',
        ),
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='accounts_us_project_2a2cf1_idx',
            old_name='accounts_usa_project_f0132b_idx',
        ),
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='accounts_us_created_8ac775_idx',
            old_name='accounts_usa_created_6d04d6_idx',
        ),
    ]
