# Generated by Django 6.0.3 on 2026-04-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_project'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingestionjob',
            new_name='documents_i_status_441675_idx',
            old_name='documents_i_status_4650eb_idx',
        ),
        migrations.RenameIndex(
            model_name='ingestionjob',
            new_name='documents_i_documen_8cdadd_idx',
            old_name='documents_i_documen_85f5f7_idx',
        ),
    ]
